//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebGym.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DetalleInventario
    {
        public int IdDetalleInventario { get; set; }
        [DisplayName("Cantidad en inventario")]
        public Nullable<int> cantidad { get; set; }
        [DisplayName("Estado del material")]
        public Nullable<int> estado { get; set; }
        public Nullable<int> IdInventario { get; set; }
    
        public virtual Inventario Inventario { get; set; }
    }
}
