//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebGym.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DetalleEjerciciosP
    {
        public int detalle_Ejercicios_P { get; set; }
        [Required(ErrorMessage = "Ingrese el tipo de ejercicio.")]
        [DisplayName("Tipo de ejercicio")]
        public string tipo { get; set; }
        [DisplayName("Cantidad de repeticiones")]
        public Nullable<int> cantidad { get; set; }
        [DisplayName("Tiempo en segundos")]
        public Nullable<int> tiempoEnSegundos { get; set; }
        [DisplayName("Fecha realizacion")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<int> IdEjercicios_P { get; set; }
    
        public virtual Ejercicios_P Ejercicios_P { get; set; }
    }
}
