//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebGym.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DetalleEjercicioT
    {
        public int IdDE { get; set; }
        [Required(ErrorMessage = "Ingrese el tipo de ejercicio.")]
        [DisplayName("Tipo de ejercicio")]
        public string tipoDeEjercicio { get; set; }
        [DisplayName("Repeticiones a realizar")]
        public Nullable<int> repeticiones { get; set; }
        public Nullable<int> IdET { get; set; }
    
        public virtual Ejercicios_T Ejercicios_T { get; set; }
    }
}
