//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebGym.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Ejercicios_P
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ejercicios_P()
        {
            this.DetalleEjerciciosP = new HashSet<DetalleEjerciciosP>();
        }
    
        public int IdEjercicios_P { get; set; }
        [Required(ErrorMessage = "Ingrese la fecha en la que se realizo el ejercicio.")]
        [DisplayName("Fecha de ejercicio")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> fecha_ej_p { get; set; }
        public Nullable<int> IdDatos { get; set; }
    
        public virtual DatosPersona DatosPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEjerciciosP> DetalleEjerciciosP { get; set; }
    }
}
