//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebGym.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Ejercicios_T
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ejercicios_T()
        {
            this.DetalleEjercicioT = new HashSet<DetalleEjercicioT>();
        }
    
        public int IdEjercicios_T { get; set; }
        [Required(ErrorMessage = "Ingrese un Dia.")]
        [DisplayName("Dia")]
        public Nullable<int> Dia { get; set; }
        public Nullable<int> IdDatos { get; set; }
    
        public virtual DatosPersona DatosPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEjercicioT> DetalleEjercicioT { get; set; }
    }
}
