//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medidas
    {
        public int idMedidas { get; set; }
        public Nullable<int> altura { get; set; }
        public Nullable<int> medidasAbd { get; set; }
        public Nullable<int> medidasCintura { get; set; }
        public Nullable<int> medidasPecho { get; set; }
        public Nullable<int> IdDatos { get; set; }
        public Nullable<System.DateTime> fecha_med { get; set; }
    
        public virtual DatosPersona DatosPersona { get; set; }
    }
}
